### ISSUE TITLE
The application suddenly stopped when I clicked the "Email" feature in the "About nusic" menu section in the application settings

### ISSUE THREAD

**Issue by ammarraisafti** [schnatterer/nusic#16]
# Expected behavior
I have successfully installed this app and run it on my android device. And I want to send an Email or contact the developer via Email, using the "Email" feature provided by the developer in the "About nusic" menu item in the application settings.

# Actual behavior
The application suddenly stops when I click the "Email" feature in the "About nusic" menu section of the app settings. And give me instructions to restart the app, after I do it, I try to access the "Email" feature again, then the app suddenly stops. And give me the instructions to get out of the app. The problem persists, although I have tried to do it repeatedly. I also uninstalled the app, then reinstalled it. But unfortunately the same problem still occurs.

# How to reproduce
* Install the latest version of "nusic" app, then open and run the app.
* Next you have to go into the application settings, then select and open the "About nusic" menu, then click the "Email" feature, then you will find the problem as I have explained.

* Browser: Samsung Galaxy S6 edge 
* Operating system: Nougat 7.0
* App version: 3.2.0

# Recording Of The Bug
https://youtu.be/EZdey25YEoA

# Logcat

<code> --------- beginning of crash
05-11 21:25:12.675 22929 22929 E AndroidRuntime: FATAL EXCEPTION: main
05-11 21:25:12.675 22929 22929 E AndroidRuntime: Process: info.schnatterer.nusic, PID: 22929
05-11 21:25:12.675 22929 22929 E AndroidRuntime: android.content.ActivityNotFoundException: Unable to find explicit activity class {info.schnatterer.nusic/info.schnatterer.nusic.android.activities.NusicWebView}; have you declared this activity in your AndroidManifest.xml?
05-11 21:25:12.675 22929 22929 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1820)
05-11 21:25:12.675 22929 22929 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1531)
05-11 21:25:12.675 22929 22929 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4399)
05-11 21:25:12.675 22929 22929 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4358)
05-11 21:25:12.675 22929 22929 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:4682)
05-11 21:25:12.675 22929 22929 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:4650)
05-11 21:25:12.675 22929 22929 E AndroidRuntime: 	at android.preference.Preference.performClick(Preference.java:1201)
05-11 21:25:12.675 22929 22929 E AndroidRuntime: 	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:289)
05-11 21:25:12.675 22929 22929 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:339)
05-11 21:25:12.675 22929 22929 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1705)
05-11 21:25:12.675 22929 22929 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:4171)
05-11 21:25:12.675 22929 22929 E AndroidRuntime: 	at android.widget.AbsListView$13.run(AbsListView.java:6735)
05-11 21:25:12.675 22929 22929 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
05-11 21:25:12.675 22929 22929 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-11 21:25:12.675 22929 22929 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
05-11 21:25:12.675 22929 22929 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6682)
05-11 21:25:12.675 22929 22929 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-11 21:25:12.675 22929 22929 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
05-11 21:25:12.675 22929 22929 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
05-11 21:25:24.789 23132 23132 E AndroidRuntime: FATAL EXCEPTION: main
05-11 21:25:24.789 23132 23132 E AndroidRuntime: Process: info.schnatterer.nusic, PID: 23132
05-11 21:25:24.789 23132 23132 E AndroidRuntime: android.content.ActivityNotFoundException: Unable to find explicit activity class {info.schnatterer.nusic/info.schnatterer.nusic.android.activities.NusicWebView}; have you declared this activity in your AndroidManifest.xml?
05-11 21:25:24.789 23132 23132 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1820)
05-11 21:25:24.789 23132 23132 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1531)
05-11 21:25:24.789 23132 23132 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4399)
05-11 21:25:24.789 23132 23132 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4358)
05-11 21:25:24.789 23132 23132 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:4682)
05-11 21:25:24.789 23132 23132 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:4650)
05-11 21:25:24.789 23132 23132 E AndroidRuntime: 	at android.preference.Preference.performClick(Preference.java:1201)
05-11 21:25:24.789 23132 23132 E AndroidRuntime: 	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:289)
05-11 21:25:24.789 23132 23132 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:339)
05-11 21:25:24.789 23132 23132 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1705)
05-11 21:25:24.789 23132 23132 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:4171)
05-11 21:25:24.789 23132 23132 E AndroidRuntime: 	at android.widget.AbsListView$13.run(AbsListView.java:6735)
05-11 21:25:24.789 23132 23132 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
05-11 21:25:24.789 23132 23132 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-11 21:25:24.789 23132 23132 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
05-11 21:25:24.789 23132 23132 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6682)
05-11 21:25:24.789 23132 23132 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-11 21:25:24.789 23132 23132 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
05-11 21:25:24.789 23132 23132 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410) </code>

**Comment by schnatterer** [comment]
Hi @ammarraisafti,

thanks for this very detailed issue!
I think this is already fixed in the code base, but not released yet.

Hopefully, I'll find some time soon to catch up on this!

**Comment by schnatterer** [comment]
This should be resolved in version [3.3.0](https://github.com/schnatterer/nusic/releases/tag/v.3.3.0). Please reopen, if error still occurrs on your device.
