### ISSUE TITLE
Logo/Icon Proposal

### ISSUE THREAD

**Issue by jbeguna04** [schnatterer/nusic#17]
Hi good day! Im Jibbie Eguna, a graphics designer, I would like to ask for your permission to propose a new designs of logo in your application/project. I would like to help projects in open-source .I would just like to propose new designs. Hoping for your positive response Thank You!

**Comment by schnatterer** [comment]
Hey @jbeguna04, nusic could definitely use a properly designed logo. I'm not a designer and just improvised the current one with minimal effort.

I'd be happy to see your proposal! The current designs reside [here](https://github.com/schnatterer/nusic/tree/develop/resources). 
What I need would be a logo and a [featured graphic/image](https://support.google.com/googleplay/android-developer/answer/1078870?hl=en).
Note that for logos/icons, Android Oreo (API 26) requires to use [adaptive icons](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive). I [tried](https://github.com/schnatterer/nusic/tree/feature/api_27) to convert the current one but the circular design does not seem to fit so perfectly anymore. Other apps, like Signal or Whatsapp have migrated to rectangular icon forms. The adaptive icons can be [created with android studio](https://developer.android.com/studio/write/image-asset-studio).

**Comment by jbeguna04** [comment]
Thank you for the respone. Please allow me to send the designs here for im still doing the designs.

**Comment by jbeguna04** [comment]
<center>Thank You for waiting. Here are the proposal of design
![image](https://user-images.githubusercontent.com/35353768/40275699-30518ed4-5c2a-11e8-9f99-6bed20d161f9.png)

Adaptive Icon:
![adaptive icon](https://user-images.githubusercontent.com/35353768/40275701-39542b22-5c2a-11e8-936c-ea587a7be5da.gif)</center>

**Comment by schnatterer** [comment]
Hey @jbeguna04, wow, those look awesome. I'm impressed!

I prefer the blue one with the shadow you used for the adaptive icon preview.

For integrating into the app and the google play store I need a [High-res icon and a Feature graphic](https://support.google.com/googleplay/android-developer/answer/1078870?hl=en). SVG would be my prefferred format. 

Please put them [here](https://github.com/schnatterer/nusic/tree/develop/resources) and open a pull request. I will then integrate the new logo int the app (and of course add you to the list of contributors ;-)) and release a new version.

Thanks!

**Comment by jbeguna04** [comment]
Pull request already made and contains the Icon and Featured Graphic in the PR. Thank You

**Comment by schnatterer** [comment]
Thank * you*! I won't hesitate to contact you :-)
