### ISSUE TITLE
Interpret: Various Artists

### ISSUE THREAD

**Issue by Solar-Simon** [schnatterer/nusic#25]
If you have one song tagged with "Various Artists" as Interpret, you get lot of random stuff into your list.
After editing the Song, all the entries where still there. Had to reset data of the app.
Ad possibility to ignore Artists?

**Comment by schnatterer** [comment]
Does long tabbing a release, then "Hide all by artist" work for you?

**Comment by Solar-Simon** [comment]
Ah nice, didn't know the longpress feature. So it is already there. Great 

Since I removed the tag and reset the app, I could not test the feature. If you need testing, I could reproduce. Otherwise I would just say: Thank you and solved :) 




-------- Ursprüngliche Nachricht --------
Von: schnatterer ***@***.***>
Gesendet: 17. Januar 2022 07:27:39 MEZ
An: schnatterer/nusic ***@***.***>
CC: Solar-Simon ***@***.***>, Author ***@***.***>
Betreff: Re: [schnatterer/nusic] Interpret: Various Artists (Issue #25)

Does long tabbing a release, then "Hide all by artist" work for you?
