### ISSUE TITLE
Get listed on MetaBrainz/supporters

### ISSUE THREAD

**Issue by Freso** [schnatterer/nusic#6]
Hello :) At @MetaBrainz we like to (try and) keep up with who's using our data. It would be great if you'd register your project at https://metabrainz.org/ so we can list you at https://metabrainz.org/supporters - AFAICT, the project is open source and not generating a profit, so the non-profit tier should fit perfectly.

I'd also like to extend an invitation for you to join us in #metabrainz and #musicbrainz on Freenode IRC, and to contact us anytime either on IRC or on [our forums](https://community.metabrainz.org/) if you have any questions or comments.

**Comment by schnatterer** [comment]
Hi @Freso, thank you very much for your invitations, I will register ASAP.

**Comment by schnatterer** [comment]
[Done](https://metabrainz.org/supporters/tiers/8)!

Are there any badges or something I can put in the [readme.md](https://github.com/schnatterer/nusic/blob/develop/README.md) to show my support for @MetaBrainz?

Finally, just some (hopefully constructive) feedback: As you might have reckoned from my email, I didn't find out right away that the "Sign up" button was the way to go ;-)
So, my suggestion is to put a hint to [signing up](https://metabrainz.org/supporters/account-type) on the [supporters page](https://metabrainz.org/supporters), in addition to ["contact us"](https://metabrainz.org/contact) (which was why I wrote the email). 

Cheers!
